print("=" * 30)
def cumprimentar(nome):
    cumprimentar(nome) ("Bem-vindo à aula.")
print(f"O teu nome em maiúsculas é: {nome.upper()}")
print("Hoje vamos aprender Git")
print("Olá turma do Python! Tudo ok?")
print("Tudo bem!")
nome: str = input("Qual é o seu nome? ")
print(f"Olá, {nome}!")
idade = input("Quantos anos tens? ")
print(f"{nome} tem {idade} anos.")
print("=" * 30)
